services:
  api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - API_KEY=${API_KEY:-verystrongpassword}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
